apiVersion: v1
data:
  aws-ebs-csi: |
    ChartName: aws-ebs-csi-driver
    ChartVersion: v2.28.1
    RepositoryURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
  cilium: |
    ChartName: cilium
    ChartVersion: 1.15.0
    RepositoryURL: https://helm.cilium.io/
  cluster-autoscaler: |
    ChartName: cluster-autoscaler
    ChartVersion: 9.35.0
    RepositoryURL: https://kubernetes.github.io/autoscaler
  nfd: |
    ChartName: node-feature-discovery
    ChartVersion: 0.15.2
    RepositoryURL: https://kubernetes-sigs.github.io/node-feature-discovery/charts
  nutanix-snapshot-csi: |
    ChartName: nutanix-csi-snapshot
    ChartVersion: v6.3.2
    RepositoryURL: https://nutanix.github.io/helm/
  nutanix-storage-csi: |
    ChartName: nutanix-csi-storage
    ChartVersion: v2.6.6
    RepositoryURL: https://nutanix.github.io/helm/
  tigera-operator: |
    ChartName: tigera-operator
    ChartVersion: v3.26.4
    RepositoryURL: https://docs.tigera.io/calico/charts
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ .Values.helmAddonsConfigMap }}
