apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    ccm: nutanix
    cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
    cluster.x-k8s.io/provider: infrastructure-nutanix
  name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - ${POD_CIDR:-192.168.0.0/16}
    serviceDomain: cluster.local
    services:
      cidrBlocks:
        - ${SERVICE_CIDR:-10.128.0.0/12}
  topology:
    class: test-cre
    controlPlane:
      metadata: {}
      replicas: ${CONTROL_PLANE_MACHINE_COUNT}
    variables:
      - name: clusterConfig
        value:
          etcd:
            image:
              repository: my-registry.io/my-org/my-repo
              tag: "v3.5.99_custom.0"
          extraAPIServerCertSANs:
            - a.b.c.example.com
            - d.e.f.example.com
          globalImageRegistryMirror:
            url: https://example.com
            credentials:
              secretRef:
                name: my-mirror-ca-cert
          proxy:
            http: http://example.com
            https: http://example.com
            additionalNo:
              - no-proxy-1.example.com
              - no-proxy-2.example.com
          imageRegistries:
            - url: https://my-registry.io
              credentials:
                secretRef:
                  name: my-registry-credentials
          kubernetesImageRepository: "my-registry.io/my-org/my-repo"
          users:
            - name: capxuser
              sshKey: ssh-key-expample-1
          nutanix:
            prismCentralEndpoint:
              host: "PC-ip-fqdn"
              port: 9440
              insecure: false
              additionalTrustBundle: "trust-bundle-root-ca"
            controlPlaneEndpoint:
              host: "api-server-ip-fqdn"
              port: 6443
            failureDomains:
              - name: fd1
                cluster:
                  name: PE1
                  type: name
                subnet:
                  - name: subnet1
                    type: name
                isControlPlane: false
          controlPlane:
            nutanix:
              machineDetails:
                bootType: legacy
                cluster:
                  name: PE1
                  type: name
                image:
                  name: image1
                  type: name
                memorySize: 4Gi
                systemDiskSize: 40Gi
                vcpuSockets: 2
                vcpusPerSocket: 1
                subnet:
                  - name: subnet1
                    type: name
                project: prj1
                additionalCategories:
                  - key1: value1
                  - key2: value2
                gpus:
                  - type: name
                    name: gpu1
                  - type: name
                    name: gpu2
          addons:
            cni:
              provider: Cilium
              strategy: HelmAddon
            csi: {}
            nfd: {}
      - name: workerConfig
        value:
          nutanix:
            machineDetails:
              bootType: legacy
              cluster:
                name: PE1
                type: name
              image:
                name: image1
                type: name
              memorySize: 4Gi
              systemDiskSize: 40Gi
              vcpuSockets: 2
              vcpusPerSocket: 1
              subnet:
                - name: subnet1
                  type: name
              project: prj1
              additionalCategories:
                - key1: value1
                - key2: value2
              gpus:
                - type: name
                  name: gpu1
                - type: name
                  name: gpu2
    version: ${KUBERNETES_VERSION}
    workers:
      machineDeployments:
        - class: ${CLUSTER_CLASS_NAME}-worker
          metadata: {}
          name: md-0
          replicas: ${WORKER_MACHINE_COUNT}
